#!/usr/bin/env bash
# print subdomain information

subdomain_func() {
    sub=$2
    record=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 )
    echo $sub $record | | awk '{ print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ $# == 1 ]
then
    subdomain_func "$1" "www"
    subdomain_func "$1" "lb-01"
    subdomain_func "$1" "web-01"
    subdomain_func "$1" "web-02"
else
    subdomain_func "$1" "$2"
fi
