#!/usr/bin/env bash
# print subdomain information

subdomain_func() {
    sub=$2
    echo $sub
    dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{ print "The subdomain " $sub " is a " $4 " record and points to " $5}'
}

if [ -z $2]
then
    subdomain_func "$1" "www"
    subdomain_func "$1" "lb-01"
    subdomain_func "$1" "web-01"
    subdomain_func "$1" "web-02"
else
    subdomain_func "$1" "$2"
fi
