#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
