#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80
# 

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
