#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update -y
sudo apt-get install haproxy -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo echo "
frontend myfrontend
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 332352-web-01 100.25.12.89:80 check
    server 332352-web-02 54.234.129.228:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
