#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update -y
sudo apt-get install haproxy -y
echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo echo "
    log global
    bind *:80
    mode http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http
    balance roundrobin
    server 332352-web-01 100.25.12.89:80 check
    server 332352-web-02 54.234.129.228:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
