#!/usr/bin/env bash
# displays Best School 10 times using while.

n=1

while (( n <= 10))
do
  if (( n == 4 ))
  then
    echo "bad luck"
  elif (( n == 8))
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( n++ ))
done
