#!/usr/bin/env bash
# displays from 1 ti 20 using while.

n=1

while (( n <= 20))
do
  echo "$n"
  if (( n == 4 ))
  then
    echo "bad luck from China"
  elif (( n == 9))
  then
    echo "bad luck from Japan"
  elif (( n == 17))
  then
    echo "bad luck from Italy"
  fi
  (( n++ ))
done
