#!/usr/bin/env bash
# displays from 1 ti 20 using while.

n=1

while (( n <= 20))
do
  echo "$n"
  case "$n" in
  4)
    echo "bad luck from China";;
  9)
    echo "bad luck from Japan";;
  17)
    echo "bad luck from Italy";;
  esac
  (( n++ ))
done
