#!/usr/bin/env bash
# bash script to fix this container so that Nginx is running as the nginx user

sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill -f apache2
sudo service nginx restart -u nginx
